"""Built-in roleplay scenarios and guided lessons (Pingo-style catalog)."""


def S(id, emoji, cat, title, title_ja, desc, ai_role, user_role, setting, vocab, levels="N5-N1"):
    return {
        "id": id, "emoji": emoji, "category": cat, "title": title, "title_ja": title_ja,
        "description": desc, "ai_role": ai_role, "user_role": user_role,
        "setting": setting, "target_vocab": vocab, "levels": levels, "kind": "roleplay",
    }


SCENARIOS = [
    # ------------------------------------------------------------ Food & Drink
    S("ramen", "🍜", "Comer y beber", "Pedir ramen", "ラーメン屋で注文",
      "Pide ramen, elige los ingredientes y paga.",
      "un camarero amable", "un cliente con hambre",
      "Una pequeña tienda de ramen de Tokio a la hora de comer.",
      ["ラーメン", "餃子", "大盛り", "注文", "おすすめ", "会計"]),
    S("izakaya", "🍻", "Comer y beber", "Una noche de izakaya", "居酒屋で一杯",
      "Pide bebidas y platos para compartir; conversa con el personal.",
      "un camarero al que le gusta conversar", "un cliente después del trabajo",
      "Un izakaya animado por la noche.",
      ["生ビール", "枝豆", "焼き鳥", "乾杯", "お通し", "とりあえず"]),
    S("cafe", "☕", "Comer y beber", "En una cafetería", "カフェで注文",
      "Pide café y un postre; pregunta por el wifi y las mesas.",
      "un barista atento", "un cliente que busca relajarse",
      "Una cafetería tranquila una tarde de lluvia.",
      ["コーヒー", "ケーキ", "席", "持ち帰り", "砂糖", "ミルク"]),
    S("sushi", "🍣", "Comer y beber", "En la barra de sushi", "寿司屋のカウンター",
      "Siéntate en la barra y pide recomendaciones al chef.",
      "un chef de sushi con experiencia", "un cliente curioso",
      "La barra de un restaurante tradicional de sushi.",
      ["握り", "まぐろ", "わさび", "お任せ", "新鮮", "醤油"]),
    S("konbini", "🏪", "Comer y beber", "En el konbini", "コンビニで買い物",
      "Compra comida, pide calentar el bentō y paga con tarjeta.",
      "un dependiente", "un cliente con prisa",
      "Una tienda de conveniencia por la noche.",
      ["温める", "お弁当", "袋", "ポイントカード", "レジ", "おにぎり"]),

    # ------------------------------------------------------------------ Travel
    S("airport", "✈️", "Viajes", "En el aeropuerto", "空港で",
      "Factura y pregunta por el equipaje y la puerta de embarque.",
      "un agente de facturación", "un viajero que vuela a Osaka",
      "El mostrador de facturación del aeropuerto de Narita.",
      ["搭乗券", "荷物", "ゲート", "出発", "パスポート", "窓側"]),
    S("train", "🚄", "Viajes", "Coger el tren", "電車に乗る",
      "Compra billetes, busca el andén y pregunta por los transbordos.",
      "un empleado de la estación", "un viajero que quiere llegar a Kioto",
      "Una estación grande con varias líneas de tren.",
      ["切符", "乗り換え", "ホーム", "指定席", "各駅停車", "終電"]),
    S("hotel", "🏨", "Viajes", "Llegar al hotel", "ホテルのチェックイン",
      "Regístrate y pregunta por el desayuno, el wifi y la salida.",
      "un recepcionista", "un huésped con reserva",
      "La recepción de un hotel.",
      ["予約", "チェックイン", "朝食", "鍵", "何時", "禁煙"]),
    S("directions", "🗺️", "Viajes", "Preguntar cómo llegar", "道を聞く",
      "Pide ayuda para encontrar la estación.",
      "una persona amable del barrio", "un turista que se ha perdido",
      "Una esquina de un barrio que no conoces.",
      ["まっすぐ", "右", "左", "信号", "交差点", "近く"]),
    S("taxi", "🚕", "Viajes", "Coger un taxi", "タクシーに乗る",
      "Indica el destino, conversa con el conductor y paga.",
      "un taxista hablador", "un pasajero",
      "Un taxi en la ciudad.",
      ["まで", "お願いします", "右に曲がって", "ここで", "お釣り", "領収書"]),
    S("ryokan", "♨️", "Viajes", "Alojarte en un ryokan", "旅館に泊まる",
      "Regístrate en una posada y pregunta por el onsen y la cena.",
      "la encargada de un ryokan", "un huésped con ganas de ir al onsen",
      "Un ryokan tradicional en la montaña.",
      ["温泉", "浴衣", "夕食", "布団", "露天風呂", "旅館"]),

    # ---------------------------------------------------------------- Shopping
    S("clothes", "👕", "Compras", "Comprar ropa", "服を買う",
      "Pregunta por tallas y colores; prueba una prenda.",
      "un dependiente atento", "un cliente que busca una chaqueta",
      "Una tienda de ropa de un centro comercial.",
      ["サイズ", "試着", "色違い", "似合う", "少し", "セール"]),
    S("electronics", "📱", "Compras", "Tienda de electrónica", "家電量販店で",
      "Compara móviles y pregunta por características y precios.",
      "un vendedor entusiasta", "un cliente que busca un móvil",
      "Una gran tienda de electrónica.",
      ["値段", "機能", "安い", "保証", "比べる", "電池"]),
    S("souvenir", "🎁", "Compras", "Comprar recuerdos", "お土産を買う",
      "Elige regalos para la familia y pide que los envuelvan.",
      "el dueño de una tienda de recuerdos", "un turista que compra regalos",
      "Una tienda de recuerdos cerca de un templo.",
      ["お土産", "包む", "有名", "人気", "別々に", "おすすめ"]),

    # -------------------------------------------------------------- Daily Life
    S("intro", "👋", "Vida diaria", "Conocer a alguien", "初めまして",
      "Preséntate: tu nombre, de dónde eres y tus aficiones.",
      "una persona japonesa que acabas de conocer", "tú mismo",
      "Un encuentro de intercambio de idiomas.",
      ["初めまして", "出身", "趣味", "仕事", "よろしく", "呼んで"]),
    S("weather", "🌦️", "Vida diaria", "Hablar del tiempo", "天気の話",
      "Comenta el tiempo de hoy y la previsión para el fin de semana.",
      "un vecino", "tú mismo",
      "Fuera de tu edificio una mañana nublada.",
      ["天気", "雨", "暑い", "寒い", "予報", "傘"]),
    S("weekend", "🎡", "Vida diaria", "Planes de fin de semana", "週末の予定",
      "Cuenta qué hiciste y qué te gustaría hacer el próximo fin de semana.",
      "un amigo curioso", "tú mismo",
      "Una comida con un amigo.",
      ["予定", "映画", "遊ぶ", "楽しみ", "疲れた", "どこか"]),
    S("hobbies", "🎸", "Vida diaria", "Tus aficiones", "趣味について",
      "Cuenta qué te gusta hacer y pregunta por sus aficiones.",
      "un nuevo amigo con muchas aficiones", "tú mismo",
      "Una conversación informal en una cafetería.",
      ["趣味", "好き", "始める", "上手", "毎週", "一緒に"]),
    S("family", "👨‍👩‍👧", "Vida diaria", "Hablar de la familia", "家族について",
      "Describe a tu familia y pregunta por la suya.",
      "un interlocutor cercano", "tú mismo",
      "Una conversación relajada entre amigos.",
      ["家族", "兄弟", "両親", "住んでいる", "何人", "ペット"]),
    S("barber", "💇", "Vida diaria", "En la peluquería", "美容院で",
      "Explica cómo quieres que te corten el pelo.",
      "un peluquero", "un cliente",
      "Una peluquería moderna.",
      ["短く", "切る", "染める", "シャンプー", "前髪", "整える"]),
    S("gym", "💪", "Vida diaria", "Apuntarte al gimnasio", "ジムに入会",
      "Pregunta por las cuotas, los horarios y las instalaciones.",
      "un empleado del gimnasio", "alguien que quiere ponerse en forma",
      "La recepción de un gimnasio.",
      ["入会", "会費", "営業時間", "見学", "運動", "月々"]),

    # ------------------------------------------------------------- Work & Study
    S("interview", "💼", "Trabajo y estudios", "Entrevista de trabajo", "面接",
      "Habla de tu experiencia, tus puntos fuertes y tu motivación.",
      "un entrevistador educado y formal", "un candidato",
      "Una sala de reuniones de una empresa japonesa.",
      ["面接", "経験", "長所", "志望動機", "頑張ります", "御社"], "N4-N1"),
    S("office", "🏢", "Trabajo y estudios", "Conversación en la oficina", "職場の雑談",
      "Saluda y conversa con un compañero antes de empezar.",
      "un compañero con más experiencia", "un empleado nuevo",
      "La cocina de la oficina antes del trabajo.",
      ["お疲れ様", "会議", "忙しい", "残業", "週末", "頑張って"]),
    S("classroom", "🎓", "Trabajo y estudios", "Primer día de clase", "初めての授業",
      "Preséntate al profesor y pregunta por el curso.",
      "un profesor de japonés amable", "un alumno nuevo",
      "El aula de una pequeña escuela de idiomas.",
      ["授業", "宿題", "質問", "教科書", "テスト", "復習"]),
    S("phone_call", "📞", "Trabajo y estudios", "Una llamada de trabajo", "電話対応",
      "Contesta al teléfono y toma un recado.",
      "un cliente que llama a la oficina", "un empleado que contesta",
      "Tu mesa de trabajo cuando suena el teléfono.",
      ["お電話ありがとうございます", "少々お待ちください", "伝言", "折り返し", "担当", "失礼します"], "N3-N1"),

    # ------------------------------------------------------------------ Social
    S("friends", "🤝", "Con amigos", "Hacer una amistad", "友達を作る",
      "Conversa con alguien en una fiesta e intercambia contactos.",
      "una persona sociable", "tú mismo",
      "Una fiesta en casa con música y aperitivos.",
      ["連絡先", "LINE", "また今度", "楽しい", "紹介", "気が合う"]),
    S("karaoke", "🎤", "Con amigos", "Noche de karaoke", "カラオケで",
      "Elige canciones, anima a tus amigos y pide bebidas.",
      "un amigo que disfruta cantando", "tú mismo",
      "Una sala de karaoke con amigos.",
      ["歌う", "曲", "上手", "次", "予約", "盛り上がる"]),
    S("date", "💕", "Con amigos", "Primera cita", "初デート",
      "Conoce a la otra persona mientras cenáis.",
      "la persona con la que tienes una cita", "tú mismo",
      "Un restaurante acogedor un viernes por la noche.",
      ["デート", "緊張", "素敵", "また会いたい", "楽しかった", "ごちそうする"]),
    S("festival", "🏮", "Con amigos", "Festival de verano", "夏祭りで",
      "Descubre puestos de comida y juegos con un amigo.",
      "un amigo que te enseña el festival", "tú mismo",
      "Un festival de verano con farolillos y yukatas.",
      ["祭り", "花火", "屋台", "浴衣", "金魚すくい", "かき氷"]),

    # ------------------------------------------------------------ Emergencies
    S("doctor", "🏥", "Pedir ayuda", "En la consulta", "病院で",
      "Describe síntomas y practica comprender indicaciones en japonés.",
      "un médico tranquilo y amable", "un paciente resfriado",
      "La consulta de una pequeña clínica.",
      ["熱", "喉", "薬", "症状", "お大事に", "アレルギー"]),
    S("pharmacy", "💊", "Pedir ayuda", "En la farmacia", "薬局で",
      "Practica pedir un medicamento y preguntar cómo tomarlo.",
      "un farmacéutico atento", "un cliente con dolor de cabeza",
      "Una farmacia del barrio.",
      ["頭痛", "薬", "一日三回", "食後", "副作用", "処方箋"]),
    S("lost", "👮", "Pedir ayuda", "Perder la cartera", "財布をなくした",
      "Denuncia la pérdida de tu cartera en un kōban.",
      "un policía que quiere ayudar", "alguien que ha perdido la cartera",
      "Un pequeño puesto de policía cerca de la estación.",
      ["財布", "なくした", "落とした", "届け", "中身", "見つかる"]),

    # -------------------------------------------------------------- Practical
    S("bank", "🏦", "Trámites", "Abrir una cuenta", "銀行口座を開く",
      "Abre una cuenta bancaria y pregunta por la tarjeta.",
      "un empleado de banca meticuloso", "un residente nuevo",
      "El mostrador de un banco japonés.",
      ["口座", "開く", "印鑑", "キャッシュカード", "手数料", "記入"], "N4-N1"),
    S("post", "📮", "Trámites", "En correos", "郵便局で",
      "Envía un paquete al extranjero y elige el tipo de envío.",
      "un empleado de correos", "un cliente que envía un paquete",
      "El mostrador de una oficina de correos.",
      ["小包", "送る", "航空便", "船便", "切手", "届く"]),
    S("apartment", "🏠", "Trámites", "Buscar piso", "部屋探し",
      "Describe tu piso ideal a un agente inmobiliario.",
      "un agente inmobiliario que habla deprisa", "alguien que busca piso",
      "Una agencia inmobiliaria.",
      ["家賃", "駅から", "間取り", "敷金", "礼金", "内見"], "N4-N1"),
    S("phone_contract", "📶", "Trámites", "Conseguir una SIM", "携帯の契約",
      "Contrata una tarifa y pregunta por los datos móviles.",
      "un empleado de telefonía", "un cliente que necesita una SIM",
      "Una tienda de telefonía móvil.",
      ["契約", "プラン", "データ", "月額", "身分証明書", "解約"], "N4-N1"),
]


def L(id, emoji, title, title_ja, objectives, vocab, levels="N5"):
    return {
        "id": id, "emoji": emoji, "category": "Lecciones", "title": title,
        "title_ja": title_ja, "description": "; ".join(objectives),
        "objectives": objectives, "target_vocab": vocab, "levels": levels,
        "kind": "lesson",
    }


LESSONS = [
    L("greetings", "🌅", "Saludos y cortesía", "あいさつ",
      ["Saludar en distintos momentos del día", "Dar las gracias y disculparte con naturalidad"],
      ["おはようございます", "こんばんは", "ありがとうございます", "すみません", "お願いします", "失礼します"]),
    L("self_intro", "🙋", "Presentarte", "自己紹介",
      ["Hacer una presentación completa", "Usar です/から correctamente"],
      ["と申します", "出身", "歳", "仕事", "趣味", "よろしくお願いします"]),
    L("numbers_shopping", "🔢", "Números y precios", "数字と値段",
      ["Contar y decir precios", "Preguntar cuánto cuesta algo"],
      ["いくら", "百", "千", "円", "高い", "安い"]),
    L("time_dates", "🕐", "Horas y fechas", "時間と日付",
      ["Decir la hora", "Hablar de días y horarios"],
      ["何時", "半", "曜日", "今日", "明日", "毎日"]),
    L("likes_dislikes", "❤️", "Gustos y preferencias", "好きと嫌い",
      ["Expresar lo que te gusta y lo que no", "Usar が好き/が嫌い/が上手"],
      ["好き", "嫌い", "大好き", "苦手", "どんな", "一番"]),
    L("daily_routine", "🌞", "Tu rutina diaria", "毎日の生活",
      ["Contar tu rutina con expresiones de tiempo", "Usar verbos básicos en forma ます"],
      ["起きます", "食べます", "行きます", "帰ります", "寝ます", "働きます"]),
    L("past_tense", "📅", "Hablar del pasado", "過去の話",
      ["Contar lo que hiciste ayer o el fin de semana", "Usar ました/ませんでした"],
      ["昨日", "先週", "行きました", "食べました", "楽しかった", "でした"], "N5-N4"),
    L("te_form", "🔗", "Conectar con la forma て", "て形で繋ぐ",
      ["Encadenar acciones con la forma て", "Pedir algo con てください"],
      ["起きて", "食べて", "行って", "見て", "してください", "それから"], "N4"),
    L("feelings", "😊", "Expresar cómo te sientes", "気持ちを伝える",
      ["Expresar emociones y estados físicos", "Reaccionar a una noticia con naturalidad"],
      ["嬉しい", "悲しい", "疲れた", "眠い", "びっくり", "大丈夫"], "N5-N4"),
    L("keigo_basics", "🙇", "Japonés formal básico", "敬語の基本",
      ["Usar keigo básico en situaciones de atención al público", "Entender expresiones formales habituales"],
      ["いらっしゃいませ", "かしこまりました", "恐れ入ります", "いただきます", "ございます", "お待ちください"], "N3-N1"),
]

ALL = {s["id"]: s for s in SCENARIOS + LESSONS}


def catalog() -> dict:
    return {"scenarios": SCENARIOS, "lessons": LESSONS}


def get(sid: str) -> dict | None:
    return ALL.get(sid)
